config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations', passwords: "users/passwords" }
  root "products#index"
  resources :products do
    resources :buyings, only:[:index, :new] do
      collection do
        get 'index', to: 'buyings#index'
        post 'pay', to: 'buyings#pay'
        get 'done', to: 'buyings#done'
      end
    end
    resources :buyings, only: :index
    collection do
      get 'search'
    end
    collection do
      get 'addsearch'
    end
    resources :exhibitings, only:[:index]
  end
  resources :categories, only: :show
  namespace :api do
    resources :products, only: [:index,:edit], defaults: { format: 'json' }
  end

  resources :users, only: [:show] do
    resources :identifications, only: [:index]
    resources :profiles, only:[:new]
    get  "exhibiting"  => "exhibitings#exhibiting" do
      resources :products, only: [:destroy] 
    end
    get  "trading"     => "exhibitings#trading"
    get  "sold"        => "exhibitings#sold"
  end
  resources :logouts, only:[:index]
  resources :signups, only:[:index]
  resources :finishings, only:[:index]
  resources :telphones, only:[:new,:create]
  resources :addresses, only:[:new,:create]
  resources :credits, only: [:index,:new,:show] do
    collection do
      post 'delete', to: 'credits#delete'
    end
  end
  resources :payings, only:[:new] do
    collection do
      post 'pay', to: 'payings#pay'
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to_active_hash :prefecture
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/commodity_condition.rb
class CommodityCondition < ApplicationRecord
  has_many :products
end

app/models/condition.rb
class Condition < ApplicationRecord
  has_many :products
end

app/models/days_before_shipment.rb
class DaysBeforeShipment < ApplicationRecord
  has_many :products
end

app/models/delivery_method.rb
class DeliveryMethod < ApplicationRecord
  has_many :products
end

app/models/identification.rb
class Identification < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to_active_hash :prefecture
  delegate :name, to: :prefecture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :product, optional: true
  mount_uploader :image, ImageUploader
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many   :pictures, dependent: :destroy
  accepts_nested_attributes_for :pictures
  belongs_to :category
  belongs_to :size
  belongs_to :brand
  belongs_to :commodity_condition
  belongs_to :shipping_charge
  belongs_to :delivery_method
  belongs_to :days_before_shipment
  belongs_to :user
  has_one    :users_product, dependent: :destroy
  has_one :buyer, class_name: 'User', through: :users_products, dependent: :destroy
  belongs_to :condition
  belongs_to_active_hash :prefecture
  attr_accessor :change

  validates :name, presence: true
  validates :explain, presence: true
  validates :prefecture_id, presence: true
  validates :price, presence: true, numericality:{only_interger: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}
  validates :category_id, presence: true
  validates :size_id, presence: true
  validates :brand_id, presence: true
  validates :commodity_condition_id, presence: true
  validates :shipping_charge_id, presence: true
  validates :delivery_method_id, presence: true
  validates :days_before_shipment_id, presence: true
  validates :user_id, presence: true
  validates :condition_id, presence: true
end

app/models/shipping_charge.rb
class ShippingCharge < ApplicationRecord
  has_many :products
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :products
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable,omniauth_providers: [:facebook, :google_oauth2]
  validates :nickname, presence: true
  validates :first_name_kanji, presence: true
  validates :family_name_kanji, presence: true
  validates :first_name_cana, presence: true
  validates :family_name_cana, presence: true
  validates :year, presence: true
  validates :month, presence: true
  validates :day, presence: true

  has_one :sns_credential, dependent: :destroy
  has_many   :users_products, dependent: :destroy
  has_many   :bought_items, class_name: 'Product', through: :users_products, dependent: :destroy
  has_one :address
  has_one    :card

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first

    if snscredential.present?
      user = User.where(id: snscredential.user_id).first
      unless user.present?
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email
        )
      end
      sns = snscredential

    else
      user = User.where(email: auth.info.email).first
      if user.present?
        sns = SnsCredential.new(
          uid: uid,
          provider: provider,
          user_id: user.id
        )
      else
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email
        )
        sns = SnsCredential.create(
          uid: uid,
          provider: provider
        )
      end
    end
    return { user: user , sns_id: sns.id }
  end
end

app/models/users_product.rb
class UsersProduct < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :another_user
  def show
  end
  private
  def another_user
    redirect_to root_path unless current_user&.id == params[:id].to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/shared/_banner.html.haml
.contents__banner
  = image_tag("https://www.mercari.com/jp/assets/img/common/jp/top/download_bg_pc.jpg?59301348", class: "contents__banner__image")
  .contents__banner__inner
    .contents__banner__inner__text
      %h スマホで簡単フリマアプリ
      %p 今すぐ無料ダウンロード
      .contents__banner__inner__text__icon
        = link_to root_path do
          = image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?3951034907", class: "contents__banner__image__inner__text__icon__mercari", width: "68")
        .contents__banner__inner__text__icon__download
          = link_to root_path do
            = image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?3951034907", height: "40", width: "133", class: "contents__banner__image__inner__text__icon__download__app")
            = image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?3951034907", height: "40", width: "133", class: "contents__banner__image__inner__text__icon__download__google")
    = image_tag("//www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?3951034907", class: "contents__banner__inner__phone")

app/views/shared/_category.html.haml
- parents = Category.where(ancestry: nil)
.categoryIndex
  %ul.categoryIndex__parents
    - parents.each do |parent|
      %li.categoryIndex__parents__parent
        = link_to category_path(parent.id) do
          .categoryIndex__parents__parent__name
            = parent.name
        %ul.categoryIndex__children
          - parent.children.each do |child|
            %li.categoryIndex__children__child
              = link_to category_path(child.id) do
                .categoryIndex__children__child__name
                  = child.name
              %ul.categoryIndex__grandchildren
                - child.children.each do |grandchild|
                  %li.categoryIndex__grandchildren__grandchild
                    = link_to category_path(grandchild.id) do
                      .categoryIndex__grandchildren__grandchild__name
                        = grandchild.name

app/views/shared/_exhibitbtn.html.haml
.contents__btn
  = link_to new_product_path do
    %div 出品
    = fa_icon "camera" , class: "contents__btn__camera"

app/views/shared/_side.html.haml
.contents__outline__side
  .contents__outline__side__nav
    .contents__outline__side__nav__list
      = link_to user_path(current_user.id) do
        .contents__outline__side__nav__list__text
          マイページ
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"
      = link_to new_user_profile_path(current_user.id) do
        .contents__outline__side__nav__list__text
          お知らせ
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"
      = link_to new_user_profile_path(current_user.id) do
        .contents__outline__side__nav__list__text
          いいね！一覧
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"
      = link_to new_product_path do
        .contents__outline__side__nav__list__text
          出品する
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"
      = link_to user_exhibiting_path(current_user.id) do
        .contents__outline__side__nav__list__text
          出品した商品 - 出品中
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"
      = link_to user_trading_path(current_user.id) do
        .contents__outline__side__nav__list__text
          出品した商品 - 取引中
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"
      = link_to user_sold_path(current_user.id) do
        .contents__outline__side__nav__list__text
          出品した商品 - 売却済み
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"
      = link_to new_user_profile_path(current_user.id) do
        .contents__outline__side__nav__list__text
          購入した商品 - 取引中
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"
      = link_to new_user_profile_path(current_user.id) do
        .contents__outline__side__nav__list__text
          購入した商品 - 過去の取引
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"
      = link_to new_user_profile_path(current_user.id) do
        .contents__outline__side__nav__list__text
          ニュース一覧
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"
      = link_to new_user_profile_path(current_user.id) do
        .contents__outline__side__nav__list__text
          評価一覧
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"
      = link_to new_user_profile_path(current_user.id) do
        .contents__outline__side__nav__list__text
          ガイド
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"
      = link_to new_user_profile_path(current_user.id) do
        .contents__outline__side__nav__list__text
          お問い合わせ
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"
    .contents__outline__side__nav__title
      メルカリ
    .contents__outline__side__nav__list
      = link_to new_user_profile_path(current_user.id) do
        .contents__outline__side__nav__list__text
          売上・振込申請
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"
      = link_to new_user_profile_path(current_user.id) do
        .contents__outline__side__nav__list__text
          ポイント
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"
    .contents__outline__side__nav__title
      設定
    .contents__outline__side__nav__list
      = link_to new_user_profile_path(current_user.id) do
        .contents__outline__side__nav__list__text
          プロフィール
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"
      = link_to new_user_profile_path(current_user.id) do
        .contents__outline__side__nav__list__text
          発送元・お届け先住所変更
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"
      = link_to credits_path do
        .contents__outline__side__nav__list__text
          支払い方法
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"
      = link_to new_user_profile_path(current_user.id) do
        .contents__outline__side__nav__list__text
          メール/パスワード
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"
      = link_to user_identifications_path(current_user.id) do
        .contents__outline__side__nav__list__text
          本人情報
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"
      = link_to new_user_profile_path(current_user.id) do
        .contents__outline__side__nav__list__text
          電話番号の確認
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"
      = link_to logouts_path do
        .contents__outline__side__nav__list__text
          ログアウト
          =fa_icon "chevron-right" , class: "contents__outline__side__nav__list__text__icon"