config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations', passwords: "users/passwords" }
  root "products#index"
  resources :products do
    resources :buyings, only:[:index, :new] do
      collection do
        get 'index', to: 'buyings#index'
        post 'pay', to: 'buyings#pay'
        get 'done', to: 'buyings#done'
      end
    end
    resources :buyings, only: :index
    collection do
      get 'search'
    end
    collection do
      get 'addsearch'
    end
    resources :exhibitings, only:[:index]
  end
  resources :categories, only: :show
  namespace :api do
    resources :products, only: [:index,:edit], defaults: { format: 'json' }
  end

  resources :users, only: [:show] do
    resources :identifications, only: [:index]
    resources :profiles, only:[:new]
    get  "exhibiting"  => "exhibitings#exhibiting" do
      resources :products, only: [:destroy] 
    end
    get  "trading"     => "exhibitings#trading"
    get  "sold"        => "exhibitings#sold"
  end
  resources :logouts, only:[:index]
  resources :signups, only:[:index]
  resources :finishings, only:[:index]
  resources :telphones, only:[:new,:create]
  resources :addresses, only:[:new,:create]
  resources :credits, only: [:index,:new,:show] do
    collection do
      post 'delete', to: 'credits#delete'
    end
  end
  resources :payings, only:[:new] do
    collection do
      post 'pay', to: 'payings#pay'
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to_active_hash :prefecture
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/commodity_condition.rb
class CommodityCondition < ApplicationRecord
  has_many :products
end

app/models/condition.rb
class Condition < ApplicationRecord
  has_many :products
end

app/models/days_before_shipment.rb
class DaysBeforeShipment < ApplicationRecord
  has_many :products
end

app/models/delivery_method.rb
class DeliveryMethod < ApplicationRecord
  has_many :products
end

app/models/identification.rb
class Identification < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to_active_hash :prefecture
  delegate :name, to: :prefecture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :product, optional: true
  mount_uploader :image, ImageUploader
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many   :pictures, dependent: :destroy
  accepts_nested_attributes_for :pictures
  belongs_to :category
  belongs_to :size
  belongs_to :brand
  belongs_to :commodity_condition
  belongs_to :shipping_charge
  belongs_to :delivery_method
  belongs_to :days_before_shipment
  belongs_to :user
  has_one    :users_product, dependent: :destroy
  has_one :buyer, class_name: 'User', through: :users_products, dependent: :destroy
  belongs_to :condition
  belongs_to_active_hash :prefecture
  attr_accessor :change

  validates :name, presence: true
  validates :explain, presence: true
  validates :prefecture_id, presence: true
  validates :price, presence: true, numericality:{only_interger: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}
  validates :category_id, presence: true
  validates :size_id, presence: true
  validates :brand_id, presence: true
  validates :commodity_condition_id, presence: true
  validates :shipping_charge_id, presence: true
  validates :delivery_method_id, presence: true
  validates :days_before_shipment_id, presence: true
  validates :user_id, presence: true
  validates :condition_id, presence: true
end

app/models/shipping_charge.rb
class ShippingCharge < ApplicationRecord
  has_many :products
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :products
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable,omniauth_providers: [:facebook, :google_oauth2]
  validates :nickname, presence: true
  validates :first_name_kanji, presence: true
  validates :family_name_kanji, presence: true
  validates :first_name_cana, presence: true
  validates :family_name_cana, presence: true
  validates :year, presence: true
  validates :month, presence: true
  validates :day, presence: true

  has_one :sns_credential, dependent: :destroy
  has_many   :users_products, dependent: :destroy
  has_many   :bought_items, class_name: 'Product', through: :users_products, dependent: :destroy
  has_one :address
  has_one    :card

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first

    if snscredential.present?
      user = User.where(id: snscredential.user_id).first
      unless user.present?
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email
        )
      end
      sns = snscredential

    else
      user = User.where(email: auth.info.email).first
      if user.present?
        sns = SnsCredential.new(
          uid: uid,
          provider: provider,
          user_id: user.id
        )
      else
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email
        )
        sns = SnsCredential.create(
          uid: uid,
          provider: provider
        )
      end
    end
    return { user: user , sns_id: sns.id }
  end
end

app/models/users_product.rb
class UsersProduct < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  before_action :authenticate_user!
  def index
    card = Card.where(user_id: current_user.id).first
    redirect_to credit_path(card.id) if card.present?
  end

  def new
    @year = [*19..30]
    @month = [*1..12]
  end

  def show
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to new_credit_path
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def delete
    card = Card.where(user_id: current_user.id).first
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    customer = Payjp::Customer.retrieve(card.customer_id)
    customer.delete
    card.delete
    redirect_to credits_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :another_user
  def show
  end
  private
  def another_user
    redirect_to root_path unless current_user&.id == params[:id].to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/credits/index.html.haml
- breadcrumb :credit
= render "layouts/breadcrumbs"
.contents__outline
  = render 'shared/side.html.haml'
  .payments
    .payments__top
      支払い方法
    .payments__contents
      .payments__contents__title
        クレジットカード一覧
      = link_to new_credit_path, class: "payments__contents__btn" do
        .payments__contents__btn
          = fa_icon "credit-card"
          クレジットカードを追加する
      .payments__contents__guide
        支払い方法について
        =fa_icon "chevron-right"
= render "shared/exhibitbtn"

app/views/credits/new.html.haml
- breadcrumb :credit_information
= render "layouts/breadcrumbs"
.contents__outline
  = render 'shared/side.html.haml'
  .credits
    .credits__top
      クレジットカード情報入力
    .payings__main
      = form_tag(pay_payings_path, method: :post, id: 'charge-form',  name: "inputForm") do
        .payings__main__input
          %span.label
            カード番号
          %span.sticker
            必須
          = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
          = image_tag("http://manual.estore.co.jp/shared/mg_sozai/card_m_all.gif",class:"cardImage")
        .payings__main__input
          %span.label
            有効期限
          %span.sticker
            必須
          %br
          .payings__selectbox
            .payings__main__input__select
              %select#exp_month{name: "exp_month", type: "text"}
                - @month.each do |month|
                  %option
                    = month
              = fa_icon "chevron-down"
            .payings__main__input__context
              月
            .payings__main__input__select
              %select#exp_year{name: "exp_year", type: "text"}
                - @year.each do |year|
                  %option
                    = year
              = fa_icon "chevron-down"
            .payings__main__input__context
              年
        .payings__main__input
          %span.label
            セキュリティコード
          %span.sticker
            必須
          = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc"
        .payings__main__info
          = link_to do
            = fa_icon "question-circle"
            カード背面の番号とは
        #card_token
        = submit_tag "追加する",class: "payings__main__button", id: "token_submit"
= render "shared/exhibitbtn"

app/views/credits/show.html.haml
- breadcrumb :credit
= render "layouts/breadcrumbs"
.contents__outline
  = render 'shared/side.html.haml'
  .payments
    .payments__top
      支払い方法
    .payments__contents 
      %section 
        .payments__contents__header
          %h1 クレジットカード一覧
          %li
            = image_tag("//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?2482339763", width:"26",height:"20",class:"payments__contents__header__list__image")
            %div
              *********
              = @default_card_information.last4
            %div
              = @default_card_information.exp_month.to_s
              \/
              = @default_card_information.exp_year.to_s.slice(2,3)
            .payments__contents__header__list__delete
              = form_tag(delete_credits_path, method: :post, id: 'charge-form',  name: "inputForm") do
                %input{ type: "hidden", name: "card_id", value: "" }
                %button{ class: "credit__btn" } 削除する
      .payments__contents__guide
        支払い方法について
        =fa_icon "chevron-right"
= render "shared/exhibitbtn"