config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations', passwords: "users/passwords" }
  root "products#index"
  resources :products do
    resources :buyings, only:[:index, :new] do
      collection do
        get 'index', to: 'buyings#index'
        post 'pay', to: 'buyings#pay'
        get 'done', to: 'buyings#done'
      end
    end
    resources :buyings, only: :index
    collection do
      get 'search'
    end
    collection do
      get 'addsearch'
    end
    resources :exhibitings, only:[:index]
  end
  resources :categories, only: :show
  namespace :api do
    resources :products, only: [:index,:edit], defaults: { format: 'json' }
  end

  resources :users, only: [:show] do
    resources :identifications, only: [:index]
    resources :profiles, only:[:new]
    get  "exhibiting"  => "exhibitings#exhibiting" do
      resources :products, only: [:destroy] 
    end
    get  "trading"     => "exhibitings#trading"
    get  "sold"        => "exhibitings#sold"
  end
  resources :logouts, only:[:index]
  resources :signups, only:[:index]
  resources :finishings, only:[:index]
  resources :telphones, only:[:new,:create]
  resources :addresses, only:[:new,:create]
  resources :credits, only: [:index,:new,:show] do
    collection do
      post 'delete', to: 'credits#delete'
    end
  end
  resources :payings, only:[:new] do
    collection do
      post 'pay', to: 'payings#pay'
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many   :pictures, dependent: :destroy
  accepts_nested_attributes_for :pictures
  belongs_to :category
  belongs_to :size
  belongs_to :brand
  belongs_to :commodity_condition
  belongs_to :shipping_charge
  belongs_to :delivery_method
  belongs_to :days_before_shipment
  belongs_to :user
  has_one    :users_product, dependent: :destroy
  has_one :buyer, class_name: 'User', through: :users_products, dependent: :destroy
  belongs_to :condition
  belongs_to_active_hash :prefecture
  attr_accessor :change

  validates :name, presence: true
  validates :explain, presence: true
  validates :prefecture_id, presence: true
  validates :price, presence: true, numericality:{only_interger: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}
  validates :category_id, presence: true
  validates :size_id, presence: true
  validates :brand_id, presence: true
  validates :commodity_condition_id, presence: true
  validates :shipping_charge_id, presence: true
  validates :delivery_method_id, presence: true
  validates :days_before_shipment_id, presence: true
  validates :user_id, presence: true
  validates :condition_id, presence: true
end

app/controllers/api/products_controller.rb
class Api::ProductsController < ApplicationController
  def index
    @childrenCategories = Category.find_by(id: params[:selected])&.children
  end
  def edit
    @pictures = Product.find(params[:id]).pictures
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :ransack
  layout "simple" ,only: [:new, :edit]
  before_action :authenticate_user!, except: [:index,:show,:search,:addsearch]
  before_action :setting_for_product, only: [:new,:edit]
  before_action :set_product, only: [:edit,:update, :show]
  before_action :another_user,only: [:edit,:update]

  def index
    @products = Product.limit(4).order("created_at DESC")
    @categories = Category.where(ancestry: nil).limit(4)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(products_params)
    if image_params
      image_params.each do |pic|
        @product.pictures.build(image: pic)
      end
      if @product&.save
        redirect_to root_path
      else
        redirect_to new_product_path
      end
    else
      redirect_to new_product_path
    end
  end

  def edit
  end

  def update
    id = @product.id
    if @product.update(products_params)
      if delete_params
        delete_params.each do |deleteID|
          Picture.find(deleteID).destroy
        end
      end
      if image_params
        image_params.each do |image|
          Picture.create(image: image, product_id: id)
        end
      end
      redirect_to user_exhibiting_path(current_user.id)
    else
      redirect_to edit_product_path(id)
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.user_id == current_user.id
      @product.destroy
      redirect_to user_exhibiting_path(current_user.id)
    end
  end

  def show
    @products = Product.all
  end

  def search
    @products = Product.where('name LIKE(?)', "%#{params[:keyword]}%")
  end

  def addsearch
    @products = @q.result(distinct: true)
    render 'products/search'
  end

  def show
    pre_id = params[:id].to_i - 1
    next_id = params[:id].to_i + 1
    @pre_product = Product.find_by(id: pre_id)
    @next_product = Product.find_by(id: next_id)
    user = User.find(@product.user_id)
    @products = Product.where(user_id: user.id).limit(6)
    @same_products = Product.where("name LIKE ?", "%#{@product.name}%").limit(6)
    redirect_to product_exhibitings_path(params[:id]) if current_user&.id == @product.user_id
  end

  private
  def setting_for_product
    @commodityConditions = CommodityCondition.all
    @days = DaysBeforeShipment.all
    @deliveryMethods = DeliveryMethod.all
    @prefectures = Prefecture.all
    @shippingCharges = ShippingCharge.all
    @size = Size.all
    @categories = Category.where(ancestry: nil)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def products_params
    params.require(:product).permit(
      :name,
      :explain,
      :prefecture_id,
      :price,
      :category_id,
      :commodity_condition_id,
      :size_id,
      :shipping_charge_id,
      :days_before_shipment_id,
      :delivery_method_id
    ).merge(
        condition_id: 1,
        user_id: current_user.id,
        brand_id: 1
    )
  end

  def image_params
    params[:image]
  end

  def delete_params
    splited = params[:product][:change].split(",")
    splited.delete("0");
    if splited.length == Product.find(params[:id]).pictures.length && !image_params
      return nil
    else
      return splited
    end
  end

  def ransack
    @categorys = Category.all
    @sizes = Size.all
    @commodity_conditions = CommodityCondition.all
    @shipping_charges = ShippingCharge.all
    @conditions = Condition.all
    @q = Product.ransack(params[:q])
  end
  def another_user
    redirect_to root_path unless current_user&.id == @product.user.id
  end
end

app/views/products/_message.html.haml
.details__messages__content__item
  .details__messages__content__item__icon
    = link_to root_path do
      = image_tag("//static.mercdn.net/images/member_photo_noimage_thumb.png", width: "40", class: "contents__header__inner__down__right__mypage__icon")
  .details__messages__content__item__right
    .details__messages__content__item__right__user
      メルカリ太郎
    .details__messages__content__item__right__message
      .details__messages__content__item__right__message__top
        メッセージです
      .details__messages__content__item__right__message__bottom
        .details__messages__content__item__right__message__bottom__clock
          = fa_icon "clock-o"
          %span 1日前
        .details__messages__content__item__right__message__bottom__flag
          = fa_icon "flag"
      .details__messages__content__item__right__message__cursor
        = fa_icon "mouse-pointer"

app/views/products/_product.html.haml
.render__wrap
  = link_to product_path(product.id) do
    .contents__product-information__pickup__categorie__products__product
      - if product.pictures.first&.image
        = image_tag(product.pictures.first.image , class: "contents__product-information__pickup__categorie__products__product__picture")
      .contents__product-information__pickup__categorie__products__product__textbox
        .contents__product-information__pickup__categorie__products__product__textbox__name
          = product.name
        .contents__product-information__pickup__categorie__products__product__textbox__num
          .contents__product-information__pickup__categorie__products__product__textbox__num__price
            $
            = product.price
          .contents__product-information__pickup__categorie__products__product__textbox__num__favorite
            =fa_icon "heart" , class: "contents__product-information__pickup__categorie__products__product__textbox__num__favorite__icon"
            7

app/views/products/edit.html.haml
- num = 0
.main.editMain
  = form_for @product, html: { class: "main__product" } do |f|
    = f.hidden_field :change, class:"hiddenForm"
    .main__product__top
      商品の情報を入力
    .main__product__item
      .main__product__item__h1
        出品画像
        %span 必須
      .main__product__item__area
        .main__product__item__area__input
          最大10枚までアップロードできます
        .main__product__item__area__flex
          %ul#uploadedListFirst.uploadedList
          %ul#uploadedListFinal.uploadedList
          = f.label :image1, class:"main__product__item__h3" do
            = f.file_field :image0,name:"image[]", multiple: true, class: "main__product__item__h3__image",style:"display:none;", accept: ".jpg, .jpeg, .png"
            = f.file_field :image1,name:"image[]", multiple: true, class: "main__product__item__h3__image",style:"display:none;", accept: ".jpg, .jpeg, .png"
            = f.file_field :image2,name:"image[]", multiple: true, class: "main__product__item__h3__image",style:"display:none;", accept: ".jpg, .jpeg, .png"
            = f.file_field :image3,name:"image[]", multiple: true, class: "main__product__item__h3__image",style:"display:none;", accept: ".jpg, .jpeg, .png"
            = f.file_field :image4,name:"image[]", multiple: true, class: "main__product__item__h3__image",style:"display:none;", accept: ".jpg, .jpeg, .png"
            = f.file_field :image5,name:"image[]", multiple: true, class: "main__product__item__h3__image",style:"display:none;", accept: ".jpg, .jpeg, .png"
            = f.file_field :image6,name:"image[]", multiple: true, class: "main__product__item__h3__image",style:"display:none;", accept: ".jpg, .jpeg, .png"
            = f.file_field :image7,name:"image[]", multiple: true, class: "main__product__item__h3__image",style:"display:none;", accept: ".jpg, .jpeg, .png"
            = f.file_field :image8,name:"image[]", multiple: true, class: "main__product__item__h3__image",style:"display:none;", accept: ".jpg, .jpeg, .png"
            = f.file_field :image9,name:"image[]", multiple: true, class: "main__product__item__h3__image",style:"display:none;", accept: ".jpg, .jpeg, .png"
            .main__product__item__h3__context
              ドラッグアンドドロップ
              またはクリックしてファイルをアップロード
    .main__product__name-explain
      .main__product__name-explain__h1
        商品名
        %span 必須
      = f.text_field :name, placeholder: "商品名（必須 40文字まで)", class:"main__product__name-explain__h1-text", value: @product.name
      .main__product__name-explain__h2
        商品の説明
        %span 必須
      = f.text_area :explain,class:"main__product__name-explain__h2-text", placeholder: '商品の説明 (必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）&#13;&#10;2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。'.html_safe, value: @product.explain
    .main__product__details
      .main__product__details__h1
        商品の詳細
      .main__product__details__sell-box
        .main__product__details__h2
          カテゴリー
          %span 必須
        .ancestry
          .ancestry__parent
            .main__product__details__h2-choice
              = f.collection_select :category_id, @categories, :id, :name, { include_blank: "---", selected:"#{@product.category.parent.parent.id}" }
              = fa_icon "chevron-down", class: "main__product__delivery__sell-box__icon"
          .ancestry__child
            .main__product__details__h2-choice
              = f.collection_select :category_id, @product.category.parent.parent.children, :id, :name, { include_blank: "---", selected:"#{@product.category.parent.id}" }
              = fa_icon "chevron-down", class: "main__product__delivery__sell-box__icon"
          .ancestry__grandChild
            .main__product__details__h2-choice
              = f.collection_select :category_id, @product.category.parent.children, :id, :name, { include_blank: "---", selected:"#{@product.category_id}" }
              = fa_icon "chevron-down", class: "main__product__delivery__sell-box__icon"
        .main__product__details__h2.main__product__details__h2--margin
          サイズ
          %span 必須
        .main__product__details__h2-choice
          = f.collection_select :size_id, @size, :id, :size, { include_blank: "---", selected:"#{@product.size_id}" }
          = fa_icon "chevron-down", class: "main__product__delivery__sell-box__icon"
        .main__product__details__h2.main__product__details__h2--margin
          ブランド
          %span.label__nini 任意
        .main__product__details__h2-choice
          = f.text_field :brand_id, placeholder: "例) シャネル" , value: @product.brand&.name
        .main__product__details__h3
          商品の状態
          %span 必須
        .main__product__details__h3-choice
          = f.collection_select :commodity_condition_id, @commodityConditions, :id, :condition, { include_blank: "---", selected:"#{@product.commodity_condition_id}" }
          = fa_icon "chevron-down", class: "main__product__delivery__sell-box__icon"
    .main__product__delivery
      .main__product__delivery__h1
        配送について
      .main__product__delivery__sell-box
        .main__product__delivery__h2
          配送料の負担
          %span 必須
        .main__product__delivery__h2-choice
          = f.collection_select :shipping_charge_id, @shippingCharges, :id, :method, { include_blank: "---", selected:"#{@product.shipping_charge_id}" }
          = fa_icon "chevron-down", class: "main__product__delivery__sell-box__icon"
        .main__product__delivery__h2.main__product__delivery__h2--margin
          配送の方法
          %span 必須
        .main__product__delivery__h2-choice
          = f.collection_select :delivery_method_id, @deliveryMethods, :id, :name, { include_blank: "---", selected:"#{@product.delivery_method_id}" }
          = fa_icon "chevron-down", class: "main__product__delivery__sell-box__icon"
        .main__product__delivery__h3
          発送元の地域
          %span 必須
        .main__product__delivery__h3-choice
          = f.collection_select :prefecture_id, @prefectures, :id, :name, { include_blank: "---", selected:"#{@product.prefecture_id}" }
          = fa_icon "chevron-down", class: "main__product__delivery__sell-box__icon"
        .main__product__delivery__h4
          発送までの日数
          %span 必須
        .main__product__delivery__h4-choice
          = f.collection_select :days_before_shipment_id, @days,:id, :days, { include_blank: "---", selected:"#{@product.days_before_shipment_id}" }
          = fa_icon "chevron-down", class: "main__product__delivery__sell-box__icon"
    .main__product__price
      .main__product__price__h1
        販売価格(300~9,999,999)
      .main__product__price__sell-box
        .main__product__price__h2
          価格
          %span 必須
          = f.number_field :price, placeholder:"例) 300", class: "main__product__price__h2-choice", value: @product.price, min: "300", max: "9999999"
          %p ￥
        .main__product__price__h3
          .main__product__price__h3__info
            販売手数料 (10%)
          .main__product__price__h3__cost
            = "￥ #{(@product.price * 0.1).round.to_s(:delimited)}"
        .main__product__price__h4
          .main__product__price__h4__info
            販売利益
          .main__product__price__h4__profit
            = "￥ #{(@product.price * 0.9).round.to_s(:delimited)}"
    .main__product__btn-box
      .main__product__btn-box__p
        = link_to root_path do
          %span 禁止されている出品
        、
        = link_to root_path do
          %span 行為
        を必ずご確認ください。
        %br
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        = link_to root_path do
          %span 偽ブランドの販売
        は犯罪であり処罰される可能性があります。
        %br
        また、出品をもちまして
        = link_to root_path do
          %span 加盟店規約
        に同意したことになります。
      = f.submit "出品する", class:"main__product__btn-box__exhibit"

      .main__product__btn-box__return
        = link_to root_path do
          .main__product__btn-box__return__box
            もどる
.loadingArea
  .loadingArea__image
    = image_tag("gif-load.gif")

app/views/products/index.html.haml
.contents__product-information
  .contents__product-information__special-feature
    = image_tag("https://www-mercari-jp.akamaized.net/assets/img/featured/camp/index/index_keyvisual.png?4148637188", class: "contents__product-information__special-feature__image")
    = fa_icon "chevron-left" , class: "contents__product-information__special-feature__icon-left"
    = fa_icon "chevron-right" , class: "contents__product-information__special-feature__icon-right"
  .contents__product-information__pickup.contents__product-information__pickup--category
    .contents__product-information__pickup__text
      ピックアップカテゴリー
    .contents__product-information__pickup__categorie
      - @categories.limit(4).each do |parent|
        .contents__product-information__pickup__categorie__text
          = parent.name
          %span 新着アイテム
        .contents__product-information__pickup__categorie__products
          - i = 0
          - parent.children.each do |child|
            - child.children.each do |grandchild|
              = render partial: "product", collection: grandchild.products.order("created_at DESC").limit(1)
              - i += 1
              - if i == 4
                - break
            - if i == 4
              - break
  .contents__product-information__pickup.contents__product-information__pickup--brand
    .contents__product-information__pickup__text
      ピックアップブランド
    .contents__product-information__pickup__categorie
      - 4.times do
        .contents__product-information__pickup__categorie__text
          新着アイテム
        .contents__product-information__pickup__categorie__products
          = render @products
= render "shared/exhibitbtn"

app/views/products/new.html.haml
.main
  = form_for @product, html: { class: "main__product" } do |f|
    .main__product__top
      商品の情報を入力
    .main__product__item
      .main__product__item__h1
        出品画像
        %span 必須
      .main__product__item__area
        .main__product__item__area__input
          最大10枚までアップロードできます
        .main__product__item__area__flex
          %ul#uploadedListFirst.uploadedList
          %ul#uploadedListFinal.uploadedList
          .removefileuploader
            = f.label :image0, class:"main__product__item__h3" do
              = f.file_field :image0,name:"image[]", multiple: true, class: "main__product__item__h3__image",style:"display:none;", accept: ".jpg, .jpeg, .png"
              = f.file_field :image1,name:"image[]", multiple: true, class: "main__product__item__h3__image",style:"display:none;", accept: ".jpg, .jpeg, .png"
              = f.file_field :image2,name:"image[]", multiple: true, class: "main__product__item__h3__image",style:"display:none;", accept: ".jpg, .jpeg, .png"
              = f.file_field :image3,name:"image[]", multiple: true, class: "main__product__item__h3__image",style:"display:none;", accept: ".jpg, .jpeg, .png"
              = f.file_field :image4,name:"image[]", multiple: true, class: "main__product__item__h3__image",style:"display:none;", accept: ".jpg, .jpeg, .png"
              = f.file_field :image5,name:"image[]", multiple: true, class: "main__product__item__h3__image",style:"display:none;", accept: ".jpg, .jpeg, .png"
              = f.file_field :image6,name:"image[]", multiple: true, class: "main__product__item__h3__image",style:"display:none;", accept: ".jpg, .jpeg, .png"
              = f.file_field :image7,name:"image[]", multiple: true, class: "main__product__item__h3__image",style:"display:none;", accept: ".jpg, .jpeg, .png"
              = f.file_field :image8,name:"image[]", multiple: true, class: "main__product__item__h3__image",style:"display:none;", accept: ".jpg, .jpeg, .png"
              = f.file_field :image9,name:"image[]", multiple: true, class: "main__product__item__h3__image",style:"display:none;", accept: ".jpg, .jpeg, .png"
              .main__product__item__h3__context
                ドラッグアンドドロップ
                またはクリックしてファイルをアップロード
    .main__product__name-explain
      .main__product__name-explain__h1
        商品名
        %span 必須
      = f.text_field :name, placeholder: "商品名（必須 40文字まで)", class:"main__product__name-explain__h1-text", value: @product.name
      .main__product__name-explain__h2
        商品の説明
        %span 必須
      = f.text_area :explain,class:"main__product__name-explain__h2-text", placeholder: '商品の説明 (必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）&#13;&#10;2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。'.html_safe, value: @product.explain
    .main__product__details
      .main__product__details__h1
        商品の詳細
      .main__product__details__sell-box
        .main__product__details__h2
          カテゴリー
          %span 必須
        .ancestry
          .ancestry__parent
            .main__product__details__h2-choice
              = f.collection_select :category_id, @categories, :id, :name, { include_blank: "---", selected:"" }
              = fa_icon "chevron-down", class: "main__product__delivery__sell-box__icon"
          .ancestry__child
          .ancestry__grandChild
        .hiddenInputForDetails
          .main__product__details__h2.main__product__details__h2--margin
            サイズ
            %span 必須
          .main__product__details__h2-choice
            = f.collection_select :size_id, @size, :id, :size, { include_blank: "---", selected:"" }
            = fa_icon "chevron-down", class: "main__product__delivery__sell-box__icon"
        .hiddenInputForDetails
          .main__product__details__h2.main__product__details__h2--margin
            ブランド
            %span.label__nini 任意
          .main__product__details__h2-choice
            = f.text_field :brand_id, placeholder: "例) シャネル" , value: @product.brand&.name
        .main__product__details__h3
          商品の状態
          %span 必須
        .main__product__details__h3-choice
          = f.collection_select :commodity_condition_id, @commodityConditions, :id, :condition, { include_blank: "---", selected:"" }
          = fa_icon "chevron-down", class: "main__product__delivery__sell-box__icon"
    .main__product__delivery
      .main__product__delivery__h1
        配送について
      .main__product__delivery__sell-box
        .main__product__delivery__h2
          配送料の負担
          %span 必須
        .main__product__delivery__h2-choice
          = f.collection_select :shipping_charge_id, @shippingCharges, :id, :method, { include_blank: "---", selected:"" }
          = fa_icon "chevron-down", class: "main__product__delivery__sell-box__icon"
        .hiddenInputForDelivery
          .main__product__delivery__h2.main__product__delivery__h2--margin
            配送の方法
            %span 必須
          .main__product__delivery__h2-choice
            = f.collection_select :delivery_method_id, @deliveryMethods, :id, :name, { include_blank: "---", selected:"" }
            = fa_icon "chevron-down", class: "main__product__delivery__sell-box__icon"
        .main__product__delivery__h3
          発送元の地域
          %span 必須
        .main__product__delivery__h3-choice
          = f.collection_select :prefecture_id, @prefectures, :id, :name, { include_blank: "---", selected:"" }
          = fa_icon "chevron-down", class: "main__product__delivery__sell-box__icon"
        .main__product__delivery__h4
          発送までの日数
          %span 必須
        .main__product__delivery__h4-choice
          = f.collection_select :days_before_shipment_id, @days,:id, :days, { include_blank: "---", selected:"" }
          = fa_icon "chevron-down", class: "main__product__delivery__sell-box__icon"
    .main__product__price
      .main__product__price__h1
        販売価格(300~9,999,999)
      .main__product__price__sell-box
        .main__product__price__h2
          価格
          %span 必須
          = f.number_field :price, placeholder:"例) 300", class: "main__product__price__h2-choice", value: @product.price, min: "300", max: "9999999"
          %p ￥
        .main__product__price__h3
          .main__product__price__h3__info
            販売手数料 (10%)
          .main__product__price__h3__cost
            \-
        .main__product__price__h4
          .main__product__price__h4__info
            販売利益
          .main__product__price__h4__profit
            \-
    .main__product__btn-box
      .main__product__btn-box__p
        = link_to root_path do
          %span 禁止されている出品
        、
        = link_to root_path do
          %span 行為
        を必ずご確認ください。
        %br
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        = link_to root_path do
          %span 偽ブランドの販売
        は犯罪であり処罰される可能性があります。
        %br
        また、出品をもちまして
        = link_to root_path do
          %span 加盟店規約
        に同意したことになります。
      = f.submit "出品する", class:"main__product__btn-box__exhibit"

      .main__product__btn-box__return
        = link_to root_path do
          .main__product__btn-box__return__box
            もどる

app/views/products/show.html.haml
.details__content
  %h1.details__content__title
    = @product.name
  .details__content__main
    .details__content__main__table
      - if @product.pictures.first&.image
        = image_tag @product.pictures.first.image, class: "details__content__main__table__main"
        - @product.pictures.each_with_index do |picture, i|
          - if i == 0
            = image_tag picture.image, class: "details__content__main__table__sub", style: "opacity: 1;"
          - else
            = image_tag picture.image, class: "details__content__main__table__sub"
    .details__content__main__margin
    .details__content__main__table
      %table.details__content__main__table
        %tbody
          %tr
            %th 出品者
            %td
              = link_to root_path , class: "details__content__main__table__right" do
                = @product.user.nickname
              .details__content__main__table__faces
                .details__content__main__table__faces__face
                  =fa_icon "smile-o", class: "details__content__main__table__faces__face__good"
                  200
                .details__content__main__table__faces__face
                  =fa_icon "meh-o	", class: "details__content__main__table__faces__face__normal"
                  10
                .details__content__main__table__faces__face
                  =fa_icon "frown-o", class: "details__content__main__table__faces__face__bad"
                  0
          %tr
            %th カテゴリー
            %td
              = link_to category_path(@product.category.parent.parent.id), class: "details__content__main__table__right" do
                = @product.category.parent.parent.name
              %br
              = link_to category_path(@product.category.parent.id) , class: "details__content__main__table__right" do
                >
                = @product.category.parent.name
              %br
              = link_to category_path(@product.category.id) , class: "details__content__main__table__right" do
                >
                = @product.category.name
          %tr
            %th ブランド
            %td
              = link_to root_path , class: "details__content__main__table__right" do
                - if @product.brand != nil
                  = @product.brand.name
          %tr
            %th 商品のサイズ
            %td
              = @product.size.size
          %tr
            %th 商品の状態
            %td
              = @product.commodity_condition.condition
          %tr
            %th 配送料の負担
            %td
              = @product.shipping_charge.method
          %tr
            %th 配送の方法
            %td
              = @product.delivery_method.name
          %tr
            %th 配送元地域
            %td
              = link_to root_path , class: "details__content__main__table__right" do
                = @product.prefecture.name
          %tr
            %th 発送日の目安
            %td
              = @product.days_before_shipment.days
  .details__content__prices
    %span.details__content__prices__price
      ¥
      = @product.price.to_s(:delimited)
    %span.details__content__prices__tax
      (税込)
    %span.details__content__prices__postage
      送料込み
  - if @product.condition_id != 2
    = link_to product_buyings_path(@product.id), class: "details__content__buy__btn" do
      .details__content__buy
        購入画面に進む
  - else
    .details__content__buy.details__content__buy__sold
      売り切れました
  .details__content__comment
    %p
      = @product.explain
  .details__content__bottom
    .details__content__bottom__left
      .details__content__bottom__left__like
        = fa_icon "heart"
        いいね! 8
      .details__content__bottom__left__report
        = fa_icon "flag"
        不適切な商品の報告
    = link_to root_path, class: "details__content__bottom__right" do
      .details__content__bottom__right
        = fa_icon "lock"
        あんしん・あんぜんへの取り組み
.details__messages
  .details__messages__content
    = render "products/message"
    .details__messages__content__margin
    = render "products/message"
  .details__messages__content
    .details__messages__content__top
      相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
    .details__messages__content__mid
      %textarea{class: "details__messages__content__mid__form"}
      = link_to root_path, class: "details__messages__content__bottom" do
        .details__messages__content__bottom
          コメントする
.details__page
  = link_to product_path(@product.id - 1), class: "details__page__pre" do
    .details__page__pre
      - if @pre_product != nil
        <
        = @pre_product.name
  = link_to product_path(@product.id + 1), class: "details__page__next" do
    .details__page__next
      - if @next_product != nil
        = @next_product.name
        >
.details__sns
  .details__sns__box
    = link_to "https://www.facebook.com/" do
      = fa_icon "facebook-square", class: "details__sns__box__facebook"
    = link_to "https://twitter.com/home?lang=ja" do
      = fa_icon "twitter-square", class: "details__sns__box__twitter"
    = link_to "https://www.pinterest.jp/" do
      = fa_icon "pinterest-square", class: "details__sns__box__pinterest"
.details__products
  = link_to root_path, class: "details__products__name" do
    .details__products__name
      = @product.user.nickname
      さんのその他の出品
  .details__products__wrap
    = render @products
  .details__products__wrap
  = link_to root_path, class: "details__products__name" do
    .details__products__name
      = @product.name
      その他の出品
  .details__products__wrap
    = render @same_products
.details__bottom
  .details__bottom__contents
    = link_to root_path, class: "details__bottom__contents__top" do
      メルカリ
    = fa_icon "angle-right"
    %span.details__bottom__contents__name
      サンダル